name: Build Android APK (Capacitor)

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: "Android Application ID (package)"
        required: false
        default: "com.example.glitch"
      app_name:
        description: "App name (launcher title)"
        required: false
        default: "Glitch Video"
      project_dir:
        description: "Folder z package.json (np. '.', 'web', 'app', 'frontend') lub 'auto'"
        required: false
        default: "auto"
      web_dir:
        description: "Katalog z buildem web (dist/build/out) lub 'auto'"
        required: false
        default: "auto"
      node_version:
        description: "Node.js version"
        required: false
        default: "20"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          
      - name: Detect project directory
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          if [[ "${{ inputs.project_dir }}" != "auto" ]]; then
            DIR="${{ inputs.project_dir }}"
            if [[ -f "$DIR/package.json" ]]; then echo "dir=$DIR" >> "$GITHUB_OUTPUT"; exit 0; else echo "::error::package.json not found in '$DIR'"; exit 1; fi
          fi
          if [[ -f package.json ]]; then echo "dir=." >> "$GITHUB_OUTPUT"; exit 0; fi
          CANDIDATE=$(find . -maxdepth 3 -type f -name 'package.json' -not -path '*/node_modules/*' -not -path '*/android/*' | head -n 1)
          if [[ -z "${CANDIDATE}" ]]; then echo "::error::No package.json found in repo (set inputs.project_dir)"; exit 1; fi
          echo "dir=$(dirname "${CANDIDATE}")" >> "$GITHUB_OUTPUT"

      - name: Show detected dir
        run: echo "Project dir = ${{ steps.detect.outputs.dir }}"

      - name: Install JS deps
        working-directory: ${{ steps.detect.outputs.dir }}
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Ensure Tailwind toolchain if PostCSS config present (optional)
        working-directory: ${{ steps.detect.outputs.dir }}
        run: |
          if [ -f postcss.config.js ]; then
            npm i -D tailwindcss@^3.4.7 postcss@^8.4.38 autoprefixer@^10.4.19
          fi

      - name: Build web app
        id: web
        working-directory: ${{ steps.detect.outputs.dir }}
        run: |
          if npm run | grep -qE "[[:space:]]build"; then npm run build; fi
          if [ "${{ inputs.web_dir }}" = "auto" ]; then
            for d in dist build out; do
              if [ -d "$d" ]; then echo "web_dir=$d" >> "$GITHUB_OUTPUT"; exit 0; fi
            done
            echo "::error::Could not find 'dist' or 'build' or 'out' in $PWD. Provide 'web_dir'."; exit 1
          else
            if [ -d "${{ inputs.web_dir }}" ]; then echo "web_dir=${{ inputs.web_dir }}" >> "$GITHUB_OUTPUT"; else echo "::error::Provided web_dir '${{ inputs.web_dir }}' does not exist"; exit 1; fi
          fi

      - name: Install Capacitor tooling
        working-directory: ${{ steps.detect.outputs.dir }}
        run: |
          npm i -D @capacitor/cli@latest
          npm i @capacitor/core@latest @capacitor/android@latest

      - name: Generate capacitor.config.json
        working-directory: ${{ steps.detect.outputs.dir }}
        run: |
          APP_ID="${{ inputs.app_id }}"
          APP_NAME="${{ inputs.app_name }}"
          WEB_DIR="${{ steps.web.outputs.web_dir }}"
          printf '{
  "appId": "%s",
  "appName": "%s",
  "webDir": "%s",
  "bundledWebRuntime": false
}
' "$APP_ID" "$APP_NAME" "$WEB_DIR" > capacitor.config.json
          cat capacitor.config.json

      - name: Add Android platform & sync
        working-directory: ${{ steps.detect.outputs.dir }}
        run: |
          npx cap add android || true
          npx cap copy
          npx cap sync

      - name: Apply Android res overrides (icons)
        working-directory: ${{ steps.detect.outputs.dir }}
        shell: bash
        run: |
          set -euo pipefail
          if [ -d android-res-overrides ]; then
            mkdir -p android/app/src/main/res
            cp -a android-res-overrides/. android/app/src/main/res/
            echo "Applied android-res-overrides"
          else
            echo "No android-res-overrides dir; skipping"
          fi

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build debug APK
        run: |
          cd "${{ steps.detect.outputs.dir }}/android"
          ./gradlew :app:assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ${{ steps.detect.outputs.dir }}/android/app/build/outputs/apk/debug/app-debug.apk
