name: Build Android APK (Capacitor)

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: "Android Application ID (package)"
        required: false
        default: "com.example.glitch"
      app_name:
        description: "App name (launcher title)"
        required: false
        default: "Glitch Video"
      web_dir:
        description: "Directory with built web assets (dist or build)"
        required: false
        default: "auto"
      node_version:
        description: "Node.js version"
        required: false
        default: "20"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install JS deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Build web app
        id: web
        run: |
          if npm run | grep -qE "[[:space:]]build"; then npm run build; fi
          if [ "${{ inputs.web_dir }}" = "auto" ]; then
            if [ -d dist ]; then echo "web_dir=dist" >> $GITHUB_OUTPUT
            elif [ -d build ]; then echo "web_dir=build" >> $GITHUB_OUTPUT
            else echo "::error::Could not find 'dist' or 'build'. Provide 'web_dir'."; exit 1; fi
          else
            if [ -d "${{ inputs.web_dir }}" ]; then echo "web_dir=${{ inputs.web_dir }}" >> $GITHUB_OUTPUT
            else echo "::error::Provided web_dir does not exist"; exit 1; fi
          fi

      - name: Install Capacitor tooling
        run: |
          npm i -D @capacitor/cli@latest
          npm i @capacitor/core@latest @capacitor/android@latest

      - name: Generate capacitor.config.json
        run: |
          APP_ID="${{ inputs.app_id }}"
          APP_NAME="${{ inputs.app_name }}"
          WEB_DIR="${{ steps.web.outputs.web_dir }}"
          cat > capacitor.config.json <<JSON
          {
            "appId": "${APP_ID}",
            "appName": "${APP_NAME}",
            "webDir": "${WEB_DIR}",
            "bundledWebRuntime": false
          }
          JSON

      - name: Add Android platform & sync
        run: |
          npx cap add android || true
          npx cap copy
          npx cap sync

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build debug APK
        run: |
          cd android
          ./gradlew :app:assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
